name: Run Tests
on:
  workflow_dispatch:
  push:
    paths: ["src/**"]
  pull_request:
    paths: ["src/**"]
jobs:
  pytest-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Conda
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: "pip install -f https://download.pytorch.org/whl/torch_stable.html -r requirements.txt"
      - name: Run Tests and Record Coverage
        run: "coverage run --source src -m pytest tests"
        working-directory: src
      - name: Export Coverage Report
        run: "coverage xml"
        working-directory: src
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: src/coverage.xml
          flags: unittests
